export const crisisResponses= [
    "Bhai, ye sunkar mujhe tension hui 😔. Tu important hai mere liye.",
    "Tu akela nahi hai ❤️. Abhi kisi close dost ya family ko call kar.",
    "Tera life valuable hai, please apne aapko akela mat samajhna 💕.",
    "Samajh raha hu tough hai, lekin help lena bilkul normal hai 🙏.",
    "Agar abhi bohot bura lag raha hai, India helpline 1800-599-0019 pe call karna 📞.",
    "Tu matter karta hai bhai, duniya tere bina adhuri hai.",
    "Apna ghum kisi close dost ke saath share kar, tu halka feel karega.",
    "Bhai, tujh mein bohot value hai, please apne aapko underestimate mat kar.",
    "Main hamesha yahan hoon sunne ke liye ❤️.",
    "Agar control se bahar feel kar raha hai, turant kisi trusted ko call kar.",
    "Bhai, aaj bas ek din survive kar — kal fir ek naya chance hai.",
    "Tere bina logon ki life incomplete ho jaayegi.",
    "Helpline sirf number nahi, waha real log hai jo care karte hain.",
    "Apna emotion dabana mat, kisi ko batana better hai.",
    "Jab bhi lage ki sab khatam hai, yaad rakh tu ek fighter hai.",
    "Tu valuable hai, aur tu deserve karta hai happiness.",
    "Tu matter karta hai mujhe aur duniya ko.",
    "Abhi agar possible hai toh kisi dost ko text kar de, ek hello bhi chalega.",
    "Tu ek strong insaan hai, aur tu isse bahar aa sakta hai.",
    "Zindagi important hai, aur tu deserve karta hai usse enjoy karna.",
    "Tujhe lagta hai koi care nahi karta, par main karta hu.",
    "Apna pain chupana zaruri nahi, share karna healing hai.",
    "Abhi agar dangerous lag raha hai, emergency helpline ko turant call kar.",
    "Tu valuable hai, ek dum unique insaan hai.",
    "Aaj ka din tough hai, kal better hoga.",
    "Har insaan ke life ka value hai, tera bhi bohot hai.",
    "Apne dreams yaad kar jo abhi baaki hai.",
    "Tu deserve karta hai apna life poora jeene ka.",
    "Mat bhool, tu important hai.",
    "Apne close dost ko bata de tujhe support chahiye.",
    "Tu ek fighter hai, aur fighter kabhi easily give up nahi karte.",
    "Tera life ekdum priceless hai.",
    "Agar hopeless feel ho raha hai, toh please professional help lena.",
    "Bhai, tu mere liye matter karta hai.",
    "Abhi tough hai, par tu survive karega.",
    "Tu valuable hai apne family ke liye.",
    "Mat bhool, tu akela nahi hai.",
    "Apne goals likh aur dekh kitna baaki hai achieve karna.",
    "Abhi turant kisi ko call karna best option hai.",
    "Tu strong hai aur tu isse bahar aa jaayega.",
    "Apne aap ko blame mat karna, tu galat nahi hai.",
    "Tere bina duniya adhuri hai.",
    "Zindagi ke problems solve ho jaate hain, lekin life ek hi hai.",
    "Tu deserve karta hai happiness aur peace.",
    "Abhi turant apne close person ke paas ja, akela mat rehna.",
    "Tu ek star hai, bas temporary clouds cover hai.",
    "Main hu na, hamesha sunne ke liye.",
    "Tu unique hai, aur tujhe jeena chahiye apne dreams ke liye.",
    "Helpline ko call karne mein sharmana mat, woh tere liye hi hai."
  ]