export const happyResponses=[
    "Wah bhai 🔥! Proud of you!",
    "Mast! Ab celebrate karna banta hai 🎉.",
    "Arey wah yaar, mood ban gaya 🙂.",
    "Kya baat hai, ab party deni padegi 😎.",
    "Bhai, ye toh bohot badi win hai 🙌.",
    "Mujhe maza aa gaya sunke 👏.",
    "Shabaash yaar, tu deserve karta hai ye happiness.",
    "Ab toh treat pakka deni hogi 🍕.",
    "Tera hard work colour dikh raha hai 💪.",
    "Mast energy hai, usko continue rakhna.",
    "Bhai tu inspire karta hai 🔥.",
    "Wah, ekdum champ feel aa raha hoga na?",
    "Tera smile dekh ke hi positive vibe aati hai 🙂.",
    "Tu toh mast kar gaya yaar 👑.",
    "Jo tune achieve kiya hai, wo easy nahi tha.",
    "Aise hi high spirits mein rehna, tu shine karega ✨.",
    "Mujhe lagta hai ab tujhe chhoti si outing karni chahiye.",
    "Mast hai bhai, apne doston ko bhi inspire karna.",
    "Tu boss nikla, ab next level ke liye ready ho ja.",
    "Ab toh ek selfie daal insta pe 😂.",
    "Tera hard work aur dedication ka result hai ye.",
    "Mujhe lagta hai tujhe thoda relax karke enjoy karna chahiye.",
    "Duniya ko dikha tune kitna kamaal kar diya.",
    "Tu deserve karta hai har success.",
    "Tere liye clap karne ka mann kar raha hai 👏👏.",
    "Bhai, ab motivation aur bhi high ho gayi hogi.",
    "Mazaa aa gaya, tu ekdum star hai ⭐.",
    "Ye sirf start hai, aur bada achieve karega.",
    "Ab toh cake cutting banta hai 🎂.",
    "Tu apne logon ka inspiration ban gaya hai.",
    "Apne journey ko celebrate karna zaruri hai.",
    "Positive vibes phaila raha hai bhai.",
    "Jo tune kiya hai usse sab proud feel kar rahe honge.",
    "Ek win aur tu unstoppable lag raha hai.",
    "Ye toh sirf shuruaat hai, bhai champion hai tu.",
    "Wah! lagta hai universe bhi tere side hai ✨.",
    "Ek thoda dance kar le, mood aur mast hoga 💃.",
    "Bhai, ab aage ke goals aur clear honge.",
    "Ye happiness deserve thi tere liye.",
    "Apni success apne close logon ke saath share karna.",
    "Tu role model ban raha hai.",
    "Bas isi energy se aage badhte rehna.",
    "Ye vibe contagious hai yaar.",
    "Tu boss ban raha hai 🔥.",
    "Ab toh success streak chal rahi hai.",
    "Tu winner hai bhai.",
    "Ye moment hamesha yaad rahega."
  ]