export const sadResponses= [
    "Samajh raha hu yaar, tough lag raha hai 😔.",
    "Bhai, tu akela nahi hai ❤️.",
    "Jo feel kar raha hai normal hai, tu weak nahi hai 🙂.",
    "Kabhi kabhi sabko aisa lagta hai, tu alone nahi hai.",
    "Mujhe pata hai tu strong hai, bas thoda waqt de 💪.",
    "Abhi situation mushkil hai, lekin tu nikal jaayega.",
    "Mat soch zyada, chhoti chhoti khushiyan pe focus kar.",
    "Arey bhai, ek deep breath le… sab manageable hai.",
    "Dil halka karna hai toh likh daal apne thoughts ek diary mein ✍️.",
    "Thoda rest le, kal naya din hai aur nayi energy.",
    "Mujhe pata hai abhi dukh hai, par yeh hamesha nahi chalega.",
    "Thoda gaana sun, mood halka ho jaayega 🎶.",
    "Bhai, jo tu sochta hai usse tu zyada capable hai.",
    "Mujhe lagta hai tujhe thoda apne fav food khana chahiye 🍫.",
    "Tu ekdum unique hai, aur tu important hai.",
    "Main yahin hu tere saath, tension nahi.",
    "Jo ghum hai woh temporary hai, tu permanent fighter hai 💪.",
    "Mat pressure le, tu deserve karta hai happiness.",
    "Tu galat nahi, tu bas human hai.",
    "Tu ek accha insaan hai aur tu matter karta hai ❤️.",
    "Kabhi kabhi rona bhi zaruri hota hai, dil halka ho jaata hai.",
    "Apna dil halka kar, jo feel kar raha hai woh share kar le.",
    "Jitna soch raha hai utna bada problem nahi hai.",
    "Thoda apni pasand ki movie dekh, mood better hoga 🎥.",
    "Jo tune already achieve kiya hai usse yaad kar.",
    "Har struggle ek din tujhe strong banayegi.",
    "Main jaanta hu tu kabhi give up nahi karega.",
    "Bhai, sab thik ho jaayega — abhi nahi toh kal.",
    "Zyada mat soch, ek chhoti smile nikal de 🙂.",
    "Har insaan ke life mein low phase aata hai, yeh bhi nikal jaayega.",
    "Apne aap pe doubt mat kar, tu already bohot acha hai.",
    "Tu galtiyon se seekhta hai, aur yeh hi growth hai.",
    "Har din ek nayi opportunity hai, kal fir chance milega.",
    "Tu deserve karta hai pyaar aur respect.",
    "Main hu na, kabhi bhi akela feel mat kar.",
    "Zindagi perfect nahi, par tu special hai.",
    "Bhai, jo log tujhe judge karte hain unhe ignore kar.",
    "Tu apne doston aur family ke liye precious hai.",
    "Sabse badi baat: tu apna best de raha hai.",
    "Thoda patience rakh, sab line pe aa jaayega.",
    "Jo khushiyan chhoti chhoti hai unhe enjoy kar.",
    "Mat bhool tu ek fighter hai.",
    "Har struggle ek din tujhe proud feel karayegi.",
    "Tu kabhi akela nahi, main hamesha hu.",
    "Zindagi ke low points hamesha temporary hote hain.",
    "Tu deserve karta hai khud pe trust karna.",
    "Mat bhool, tu already kaafi kuch achieve kar chuka hai.",
    "Har insaan ke life mein ups and downs hote hain.",
    "Main hamesha yahan hu, chahe jo bhi ho."
  ]