export const stressResponses= [
    "Ek chhoti si list bana aur ek ek kaam karna start kar 🙌.",
    "Thoda break le yaar, paani pee aur fresh ho ja 🙂.",
    "Bhai, 5 min walk kar, mood halka ho jaayega 💨.",
    "Ek kaam kar — ek kaam complete kar ke phir reward de apne aapko 🎉.",
    "Jo control mein hai uspe focus kar, baaki chhod de abhi ke liye 💪.",
    "Apna workspace thoda saaf kar, clutter kam hoga toh stress bhi kam hoga.",
    "Pomodoro try kar — 25 min kaam, 5 min break.",
    "Tension ko likh kar dekh, dimaag halka hoga.",
    "Phone side mein rakh, ek ghanta distraction-free kaam kar.",
    "Stress hai toh ek chhoti si stretch kar, body bhi relax hogi.",
    "Ek dost ko call kar ke 5 min masti kar le, fir fresh ho kar kaam.",
    "Tension ko thoda exercise mein nikal de 💪.",
    "Kaam ko pieces mein tod, ek ek karke karna easy ho jaayega.",
    "Overthink mat kar, bas start kar de. Action lene se stress kam hoga.",
    "Bhai, ek garam chai bana aur fir kaam pe lag ja ☕.",
    "Aaj ka ek hi kaam target rakh, baaki kal.",
    "Apni achievements yaad kar, confidence boost hoga.",
    "Ek positive playlist laga, kaam enjoyable ban jaayega 🎶.",
    "Stress ko bol, tu mere upar control nahi karega 😎.",
    "Kal ki tension aaj mat la, ek din ek time pe.",
    "Jo urgent hai usse pehle complete kar, fir baaki.",
    "Bhai, ek quick nap le le power recharge ke liye.",
    "Thoda outdoor time le, hawa change se stress kam hota hai.",
    "Apne kaam ke beech 2–3 chhote breaks jaruri hai.",
    "Ek baar apni progress dekh, tujhe motivation milegi.",
    "Tension ko avoid nahi karna, solve karna hai — ek ek step mein.",
    "Overload lag raha hai toh ek kaam kisi aur ko assign kar.",
    "Apna din time-block karke chal, sab manageable lagega.",
    "Har problem ka solution hai, tu chill kar.",
    "Ek motivational video dekh, energy boost hogi.",
    "Apne upar trust kar, tu kar lega 💪.",
    "Bhai, tujhse better koi nahi handle kar sakta.",
    "Kaam karne ke baad apna fav food order kar treat ke liye 🍔.",
    "Stress ko ignore karne se nahi, action lene se solve hota hai.",
    "Har kaam ek time pe, multitask mat kar.",
    "Thoda walk kar aur apne dimaag ko fresh kar.",
    "Har insaan stress feel karta hai, tu akela nahi hai.",
    "Mat bhool, tu control mein hai, stress nahi.",
    "Chhoti chhoti victories celebrate kar.",
    "Tension kam karne ke liye 5 deep breaths le.",
    "Thoda apne hobbies ko time de, stress release hoga.",
    "Ek baar apne goals likh, clarity aayegi.",
    "Tujhe jitna lag raha hai utna mushkil nahi hai.",
    "Bas ek kaam complete karna shuru kar, flow aajayega.",
    "Stress ko ek challenge samajh aur usse beat kar.",
    "Apne doston ke saath thoda laugh kar le 😂.",
    "Apna favourite gana sun aur kaam kar.",
    "Tu already capable hai isko handle karne ke liye."
  ]